### ISSUE TITLE
Container won't start - No file or directory bash

### ISSUE THREAD

**Issue by rg9400** [rix1337/docker-myjd-api#4]
After the latest updates today( https://github.com/rix1337/docker-myjd-api/commit/4e6e99304f98643fa1c91874d276b666dab49086 and https://github.com/rix1337/docker-myjd-api/commit/9e00e88a265ab624c43c55bdc2352fd72d5f7e80), my container refuses to start. My docker logs are just saying `no file or directory bash`.

**Comment by SkalCore** [comment]
the same error also for me

**Comment by robson90** [comment]
Got the same problem.

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 
: No such file or directory bash
[cont-init.d] 10-adduser: exited 111.
[cont-init.d] 30-install: executing... 
: No such file or directory bash
[cont-init.d] 30-install: exited 111.
[cont-init.d] done.
[services.d] starting services
: No such file or directory bash
[services.d] done.
: No such file or directory bash
: No such file or directory bash
: No such file or directory bash
: No such file or directory bash
: No such file or directory bash
: No such file or directory bash
: No such file or directory bash
: No such file or directory bash
: No such file or directory bash
: No such file or directory bash
: No such file or directory bash`

If any information is needed, let me know.

**Comment by rix1337** [comment]
Hey guys, I migrated all my repos to a more streamlined, automated and frequent build structure that relies on Github actions.

If there are any issues, let me know
